project:
  type: website
  output-dir: docs

website:
  title: "Dr Jade Maggs"
  description: "Fisheries Data Scientist | Fisheries Science & Monitoring, Data Systems & Information Management, Analytics & Decision Support, Automation & Digital Solutions"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: experience.qmd
        text: Experience
      - href: research.qmd
        text: Research
    right:
      - icon: github
        href: https://github.com/jademaggs
      - icon: linkedin
        href: https://www.linkedin.com/in/jade-maggs-phd-5a091729/

  page-footer:
    center: "Dr Jade Maggs | Brisbane, Australia | jademaggs@gmail.com"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
