---
title: "Publications"
---

## Research output

My full publication list is available on [ResearchGate](https://www.researchgate.net/profile/Jade_Maggs) and [Scopus](https://www.scopus.com/authid/detail.uri?authorId=55250227800).

| | |
|---|---|
| Peer-reviewed journal articles | 24 |
| Technical reports | 81 |
| Conference presentations | 22 |
| Working group presentations | 21 |
| Book sections | 1 |
| Popular articles | 16 |
| **Scopus h-index** | **13** |

## Research themes

My published work spans three main areas:

**Recreational fisheries**  
Survey design, harvest estimation, and CPUE standardisation for inshore finfish and rock lobster fisheries in South Africa and New Zealand.

**Fish movement and behaviour**  
Acoustic telemetry studies on the movement of coastal reef fish species in southern Africa, including implications for MPA design and fisheries management.

**Marine protected areas**  
Monitoring fish assemblages in MPAs, evaluating MPA effectiveness, and contributing to MPA network design processes.

## Selected publications

*Listed chronologically, most recent first. **Maggs JQ** in bold.*

**Maggs JQ**, Holdsworth JC, Curtis S, Evans OE, Bodie CEH, Madden BK. *in press*. Estimating total post-release mortality in a boat-based recreational fishery. *Fisheries Management and Ecology*.

Martinez S, Bernard ATF, Speed CW, Mann BQ, Olbers JM, **Maggs JQ**, Floros C, Meekan MG, Yon A. 2024. Elasmobranch assemblage structure on protected high-latitude coral reefs of southeast Africa. *Marine Ecology Progress Series* 749: 87--107. <https://doi.org/10.3354/meps14717>

Smallwood CB, Ryan KL, Flanagan EA, **Maggs JQ**, Ochwada-Doyle FA, Tracey SR. 2024. Spiny lobster recreational fisheries in Australia and New Zealand: An overview of regulations, monitoring, assessment and management. *Fisheries Research* 280: 107149. <https://doi.org/10.1016/j.fishres.2024.107149>

Goetze J, Heithaus MR, MacNeil MA, [...], **Maggs JQ**, [...]. 2024. Directed conservation of the world's reef sharks and rays. *Nature Ecology & Evolution* 8: 1118--1128. <https://doi.org/10.1038/s41559-024-02386-9>

**Maggs JQ**, Evans O, Holdsworth JC, Lumley T, Hartill BW. 2024. Post-release mortality of line-caught snapper *Chrysophrys auratus* depends on hook site and capture depth. *Fisheries Management and Ecology* 31(4): e12702. <https://doi.org/10.1111/fme.12702>

Johnson KS, **Maggs JQ**, Taylor R, Evans OE, Armiger H. 2024. Estimation of recreational harvest of red and packhorse rock lobster in the CRA 1 area (2022--23). *New Zealand Fisheries Assessment Report* 2024/54. 21 p. <https://fs.fish.govt.nz/Page.aspx?pk=113&dk=25792>

**Maggs JQ**, Evans OE, Taylor R, Armiger H, Marsh C, Hartill BW. 2024. Monitoring of recreational harvest of red rock lobster *Jasus edwardsii* in CRA 2. *New Zealand Fisheries Assessment Report* 2024/52. 41 p. <https://fs.fish.govt.nz/Page.aspx?pk=113&dk=25801>

**Maggs JQ**, Armiger H, Evans O, Taylor R, Davey N, Payne G, Miller A, Spong K, Parkinson D, Bian R, Hartill BW. 2024. Trends in recreational boat effort and harvest from 2004--05 to 2022--23. *New Zealand Fisheries Assessment Report* 2024/53. 60 p. <https://fs.fish.govt.nz/Page.aspx?pk=113&dk=25806>

Davey NK, Johnson KS, **Maggs JQ**. 2024. Mean weight estimates for recreational fisheries in 2022--23. *New Zealand Fisheries Assessment Report* 2024/28. 39 p. <https://fs.fish.govt.nz/Page.aspx?pk=113&dk=25758>

**Maggs JQ**, Parsons D. 2023. Design for catch sampling programme to estimate the age structure of New Zealand hāpuku (*Polyprion oxygeneios*). *New Zealand Fisheries Assessment Report* 2023/34. 30 p. <https://fs.fish.govt.nz/Page.aspx?pk=113&dk=25522>

**Maggs JQ**, Davey NK, Hartill BW. 2023. Monitoring the Kaikōura and Motunau boat-based marine amateur fisheries for blue cod, sea perch and rock lobster, 2021--22. *New Zealand Fisheries Assessment Report* 2023/33. 53 p. <https://fs.fish.govt.nz/Page.aspx?pk=113&dk=25548>

Simpfendorfer CA, Heithaus MR, Heupel MR, [...], **Maggs JQ**, [...], Chapman D. 2023. Widespread diversity deficits of coral reef sharks and rays. *Science* 380: 1155--1160. <https://doi.org/10.1126/science.ade4884>

Mann BQ, **Maggs JQ**, Porter SN, Dalton WN. 2022. Monitoring the effects of spatial protection on the reef fish communities of the Pondoland Marine Protected Area, Eastern Cape Province, South Africa. *African Journal of Marine Science* 44(2): 1--17. <https://doi.org/10.2989/1814232X.2022.2047782>

Dames V, Bernard ATF, Floros C, Mann B, Speed C, **Maggs J**, Laing S, Meekan M, Olbers J. 2020. Zonation and reef size significantly influence fish population structure in an established marine protected area, iSimangaliso Wetland Park, South Africa. *Ocean & Coastal Management* 185: 105040. <https://doi.org/10.1016/j.ocecoaman.2019.105040>

MacNeil MA, Chapman D, Heupel M, [...], **Maggs JQ**. 2020. Global status and conservation potential of reef sharks. *Nature* 583: 801--806. <https://doi.org/10.1038/s41586-020-2519-y>

Murray TS, Cowley PD, Mann BQ, **Maggs JQ**, Gouws G. 2019. Movement patterns of an endemic South African sparid, the black musselcracker *Cymatoceps nasutus*, determined using mark-recapture methods. *African Journal of Marine Science* 41(1): 71--81. <http://dx.doi.org/10.2989/1814232X.2019.1574238>

**Maggs JQ**, Cowley PD, Porter SN, Childs AR. 2019. Should I stay or should I go? Intra-population variability in movement behaviour of wide-ranging and resident coastal fishes. *Marine Ecology Progress Series* 619: 111--124. <https://doi.org/10.3354/meps12953>

Heyns-Veale ER, Bernard ATF, Götz A, Mann BQ, **Maggs JQ**, Smith MKS. 2019. Community-wide effects of protection reveal insights into marine protected area effectiveness for reef fish. *Marine Ecology Progress Series* 620: 99--117. <http://dx.doi.org/10.3354/meps12970>

**Maggs J**, Parker D, Kerwath S, Attwood C, da Silva C, Winker H. 2017. The 2017 assessment of slinger (*Chrysoblephus puniceus*) for the South African linefishery. Report of the Linefish Scientific Working Group, LSWG No. 01, 2017: 27 pp.

**Maggs JQ**, Cowley PD. 2016. Nine decades of fish movement research in southern Africa: a synthesis of research and findings from 1928 to 2014. *Reviews in Fish Biology and Fisheries* 26(3): 287--302. <https://doi.org/10.1007/s11160-016-9425-2>

**Maggs JQ**, Mann BQ, Potts WM, Dunlop SW. 2015. Traditional management strategies fail to arrest a decline in the CPUE of an iconic marine recreational fishery species with evidence of hyperstability. *Fisheries Management and Ecology* 23(3--4): 187--199. <http://dx.doi.org/10.1111/fme.12125>

Mann BQ, Winker H, **Maggs JQ**, Porter S. 2016. Monitoring the recovery of a previously exploited surf-zone fish community in the St Lucia Marine Reserve, South Africa, using a no-take sanctuary area as a benchmark. *African Journal of Marine Science* 38(3): 423--441. <https://doi.org/10.2989/1814232X.2016.1224779>

Mann BQ, **Maggs JQ**, Khumalo MC, Khumalo D, Parak O, Wood J, Bachoo S. 2015. KwaZulu-Natal Boat Launch Site Monitoring System: A novel approach for improved management of small vessels in the coastal zone. *Ocean and Coastal Management* 104(2015): 57--64. <https://doi.org/10.1016/j.ocecoaman.2014.12.003>

Dunlop SW, Mann BQ, Cowley PD, Murray TS, **Maggs JQ**. 2015. Movement patterns of *Lichia amia* (Teleostei: Carangidae): results from a long-term cooperative tagging project in South Africa. *African Journal of Zoology* 50(3): 249--257. <http://dx.doi.org/10.1080/15627020.2015.1058724>

**Maggs JQ**, Mann BQ, Cowley PD. 2013. The contribution of a large no-take area to the management of four heavily exploited near-shore linefish species along the south-east African coast. *Fisheries Research* 144(2013): 38--47. <https://doi.org/10.1016/j.fishres.2012.10.003>

**Maggs JQ**, Mann BQ, Cowley PD. 2013. Reef fish display station-keeping and ranging behaviour in the Pondoland Marine Protected Area on the east coast of South Africa. *African Journal of Marine Science* 35(2): 183--193. <https://doi.org/10.2989/1814232X.2013.798152>

Floros C, Schleyer MH, **Maggs JQ**. 2013. Fish as indicators of diving and fishing pressure on high-latitude coral reefs. *Ocean and Coastal Management* 84: 130--139. <https://doi.org/10.1016/j.ocecoaman.2013.08.005>

**Maggs JQ**, Mann BQ, van der Elst RP. 2012. Long-term trends in the management of the recreational shore-fishery for elf (*Pomatomus saltatrix*: Pomatomidae) in KwaZulu-Natal, South Africa. *African Journal of Marine Science* 34(3): 401--410. <http://dx.doi.org/10.2989/1814232X.2012.709959>

Mann BQ, Pradervand P, **Maggs JQ**, Wintner S. 2012. A characterisation of the paddle-ski fishery in KwaZulu-Natal, South Africa. *African Journal of Marine Science* 34(1): 119--130. <https://doi.org/10.2989/1814232X.2012.675120>

Floros C, Schleyer MH, **Maggs JQ**, Celliers L. 2012. Baseline assessment of high-latitude coral reef fish communities in southern Africa. *African Journal of Marine Science* 34(1): 55--69. <http://dx.doi.org/10.2989/1814232X.2012.673284>

**Maggs JQ**, Floros C, Pereira MAM, Schleyer MH. 2010. Rapid visual assessment of fish communities on selected reefs in the Bazaruto Archipelago. *Western Indian Ocean Journal of Marine Science* 9(1): 115--134.

**Maggs JQ**. 2014. Game fish migrations. In: Goble BJ, van der Elst RP and Oellerman LK (eds). Ugu Lwethu -- Our coast: a profile of coastal KwaZulu-Natal. Department of Agriculture and Environmental Affairs and the Oceanographic Research Institute, Cedara, p87.

**Maggs JQ**. 2022. Bottom trawling by the vessel FV Chips in relation to the Napier Port Offshore Disposal Area. NIWA Client Report 2022199AK: 42.

**Maggs JQ**, Mann BQ, Els M, Khumalo D, Mselegu X. 2017. National Marine Linefish System: KZN recreational fisheries monitoring data collection by Ezemvelo KZN Wildlife: 2016 Annual Report. Oceanographic Research Institute, Durban: 60 pp. (ORI Unpublished Report 342).

**Maggs JQ**, Mann BQ. 2016. Pondoland Marine Protected Area: Ten years (2006--2016) of monitoring the effectiveness of the Pondoland MPA in protecting offshore reef-fish. Oceanographic Research Institute, Durban: 27 pp. (ORI Unpublished Report 329).

**Maggs JQ**, Dunlop SD, Mann BQ. 2012. National Marine Linefish System: A snapshot evaluation of recreational data collection by Ezemvelo KwaZulu-Natal Wildlife during 2009 and 2010 with recommendations for improvement. Oceanographic Research Institute, Durban: 39 pp. (ORI Unpublished Report 296).

[View full list on ResearchGate](https://www.researchgate.net/profile/Jade_Maggs){.btn .btn-outline-primary}
